# Generated by Django 2.0.6 on 2019-06-11 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=250)),
                ('Subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('mobile', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('age', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('picture', models.FileField(default='generic-user-purple.jpg', upload_to='profile_images/')),
                ('degree', models.FileField(upload_to='Degree')),
                ('certificate', models.FileField(upload_to='Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Talk_to_lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=250)),
                ('Subject', models.CharField(max_length=50)),
                ('Lawyer', models.CharField(max_length=100)),
            ],
        ),
    ]
